### PR TITLE
Updates to Combynify

### PR DESCRIPTION
**Pull request by tbranyen**
Hey @chesles not sure if you're planning on maintaining this module anymore, and if not, I'd be happy to take over!

I've made a few updates, namely add in the ability to have combynify recursively optimize all filters, partials, and extends into a single bundle.

### CODE REVIEW

**Comment by tbranyen** [comment]
Oh yeah and I added semicolons, would be happy to remove them as I know everyone has their preferences.

**Comment by chesles** [comment]
Awesome, thanks for the updates! I haven't been using this much lately - added you as a collaborator here. I can add you on npm too - is your username the same?

**Comment by tbranyen** [comment]
Yup, the same.  Thanks!

**Comment by chesles** [comment]
You're an owner on npm now:

```
$ npm owner ls combynify
chesles <john@chesl.es>
tbranyen <tim@tabdeveloper.com>
```

**Comment by tbranyen** [comment]
Awesome, thanks again!

**Pull request merged**
